### ISSUE TITLE
bug: Registration emails not being received

### ISSUE THREAD

**Issue by InsaneSplash** [jawug/WUGMS-Services-API#1]
When registering an account for a new user, the validation email is not being received. Trying to reset the password provides the following error with no way to re-send the activation email.

> Your account status is "pending". That means you still need to click on the URL in the email that was sent to you, when you registered, so that you can access your account.

**Comment by ThatOneNeji** [comment]
Have you checked your spam folder?

**Comment by ThatOneNeji** [comment]
This project has no email functions and does not have any user functions.
The issue is not on this project.
